# Обработка ошибок, "try..catch"

Если в скрипте возникает ошибка, то скрипт сразу "падает" и останавливается на том месте, где возникла ошибка.

```js
try {
  // Сначала выполняется этот код
} catch (err) {
  // Если ошибка возникла внутри try, то выполняется catch.
}
```

## Важные моменты

- `try..catch` работает только для ошибок, которые движок JS понимает. Т.е если код синтаксически абсолютно неверный, то
  `catch` не сработает
- `try..catch` работает синхронно. Т.е условные `setTimeout` внутри `try` не сработают.

## Объект ошибки

Она попадает в блок `catch (err) {}`.

Для встроенных ошибок основные свойства:

- `err.name` - Имя ошибки. Например `ReferenceError`
- `err.message` - Текстовое сообщение о деталях ошибки.
- `err.stack` - Текущий стек вызова.

## Блок catch без переменной

Если нам не нужна ошибка в `catch`, можно пропустить, но в некоторых браузерах может понадобиться полифилл.

## Оператор throw

Оператор `throw` генерирует ошибку. Можно передать даже примитив, но лучше наследоваться от встроенных классов ошибок.

## Проброс исключения

Блок `catch` должен обрабатывать только те ошибки, которые ему известны, и «пробрасывать» все остальные.

```js
catch(e) {

  if (e.name == "SyntaxError") {
    alert( "JSON Error: " + e.message );
  } else {
    throw e; // проброс (*)
  }

}
```

## Finally

Выполняется когда `try` отработал без ошибок, либо отработал `catch`.

## Глобальный catch

В `Node.js` есть `process.on("uncaughtException")`. 
В браузере `window.onerror = function(message, url, line, col, error)`

Используется в основном для логирования непредвиденных ошибок.
